services:
  trav_est_nvidia:
    extends:
      file: docker-compose-gui.yaml
      service: trav_est
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
